# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#publishing-using-gradle

name: ForageCraft

on:
  push:
    branches:
      - 1.16.x
    paths-ignore:
      - 'versioninfo/**'
      - 'README.md'
      - 'LICENSE'
      - 'changelog.json'
      - '.gitignore'
      - '.gitattributes'
    tags-ignore:
      - '*.*'
  schedule:
    - cron: '0 12 * * 2,6'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Update CI Workspace
        uses: actions/checkout@v1

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          java-package: jdk
          architecture: x64

      - name: Retrieve any cached dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build ForageCraft
        uses: eskatos/gradle-command-action@v1
        with:
          gradle-version: 6.8.1
          arguments: build --no-daemon --warning-mode none

      - name: Prepare to upload the build outputs
        run: |
          echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
          echo "Ready to upload the build output to GitHub."

      - name: Upload ForageCraft to GitHub
        uses: actions/upload-artifact@v2
        with:
          # Artifact name
          name: foragecraft-${{ env.SHORT_SHA }}
          # A file, directory or wildcard pattern that describes what to upload
          path: build/libs/*.jar

  test:
    name: Server Test
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
      - name: Update CI workspace
        uses: actions/checkout@v1

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          java-package: jdk
          architecture: x64

      - name: Prepare to test a Minecraft Server
        shell: pwsh
        run: |
          Write-Host "Generating the Minecraft Server's runtime environment..."
          New-Item run/server -ItemType Directory -ea 0
          "eula=true" | Out-File run/server/eula.txt
          "TEST FAILED" | Out-File run/server/TESTSERVER.txt
          Write-Host "Ready to test the Minecraft Server."

      - name: Retrieve any cached dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-serverTest-${{ matrix.os }}-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-serverTest-${{ matrix.os }}-

      - name: Run test server
        uses: eskatos/gradle-command-action@v1
        continue-on-error: true
        with:
          gradle-version: 6.8.1
          arguments: runTestServer --max-workers 1 -x downloadAssets

      - name: Read server test result
        id: log
        uses: andstor/file-reader-action@v1
        with:
          path: run/server/TESTSERVER.txt

      - name: Determine if server test was unsuccessful
        if: contains(steps.log.outputs.contents, 'TEST FAILED')
        shell: pwsh
        run: |
          Write-Host "GitHub Actions was unable to successfully load the test server into a temporary world. Check the log in the `"Run test server`" step to see what went wrong."
          exit 1
